version: '3.7'

services:

  react_app:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production